### ISSUE TITLE
snapping does not work

### ISSUE THREAD

**Issue by VicPrzz00** [RoxDevvv/Unity-Blender-Control-Style#1]
hi, the asset works fine for what its supposed to do, I just would like a couple changes if possible: Snapping when pressing Control like when moving with the built in unity tools, and also to disable (again, if possible) the shortcuts when moving in the viewport with left click and WASD

**Comment by RoxDevvv** [comment]
Please give me an example of how it works, a video example would be awesome!

**Comment by VicPrzz00** [comment]
https://github.com/RoxDevvv/Unity-Blender-Control-Style/assets/148383236/7c0a40f2-9862-4c1e-82c3-73955a0865a8
here, at first you can see how it works in unity by default when holding CTRL, and then with the scripts its smooth control only with no snapping (sorry if the video quality is bad, I had to compress it for github)

**Comment by RoxDevvv** [comment]
I added a new feature related to your idea but works same way as blender does

**How it works :** 
Select an object press R and type a number which is angle in our case 
if you want to change the direction of the angle just press minus (-) sign

https://github.com/RoxDevvv/Unity-Blender-Control-Style/assets/51464152/84b8a1dd-17ed-4c7b-96e0-c03f1d00f49c

the same way for scale and move

I will keep the issue open cause I still want to make it work with mouse dragging + Snap increment tool
I am trying to figure out how to access unity snapping API so I get the values of rotation , move and scale
![image](https://github.com/RoxDevvv/Unity-Blender-Control-Style/assets/51464152/fee9403b-7a4f-4e20-a9f6-e9728184c573)
**Edit 1** I found the way and am working on implementation 🙌
let me know what you think 😊

**Comment by RoxDevvv** [comment]
Now snapping should work 
Press S to scale select axis if you want by pressing x,y,z press ctrl to enable snapping move mouse

**Comment by VicPrzz00** [comment]
Incredible! Everything works perfectly now! Great job man, and thanks a lot! Closing the issue
